name: Pipeline CI/CD

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  test_pipeline:
    runs-on: ubuntu-latest

    steps:
      # -----------------------
      # 1. Checkout code
      # -----------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # -----------------------
      # 2. Setup Python
      # -----------------------
      - name: Setup Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # -----------------------
      # 3. Install dependencies
      # -----------------------
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install jsonschema

      # -----------------------
      # 4. Run CI/CD pipeline test
      # -----------------------
      - name: Run full pipeline CI test
        run: |
          python -m tests.test_pipeline_full_ci

      # -----------------------
      # 5. Optional: Upload final passfile for inspection
      # -----------------------
      - name: Upload final passfile as artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: final_passfile_ci
          path: dummy_chunks/final_passfile_ci.json
